# this file is to run required containers for the project eg: sql server for development
services:
  mysql:
    image: mysql:latest
    container_name: mini-stock-tracker
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mini-stock-tracker
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mini-stock-tracker:/var/lib/mysql

volumes:
  mini-stock-tracker:
