services:
  postgres:
    image: postgres:15
    container_name: mini-stock-tracker-postgres
    restart: always
    environment:
      POSTGRES_DB: mini-stock-tracker
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - mini-stock-tracker-v:/var/lib/postgresql/data

volumes:
  mini-stock-tracker-v: